Start BB implementation
BaseCollab/RISCV-Simulator pull request #33
Opened 2023-11-08 21:30 UTC by Stan1slavssKy

2023-11-23 20:12 UTC, Vokerlee requested changes

2023-11-23 20:12 UTC, Vokerlee commented on simulator/hart/basic_block.cpp
> +        if (instr->IsBranch()) {
May be use UNLIKELY()?

2023-11-23 20:12 UTC, Vokerlee commented on simulator/hart/basic_block.cpp
> +        instr->pc = curr_pc;
Is it necessary?

2023-11-23 20:12 UTC, Vokerlee commented on simulator/hart/hart.cpp
> +        DumpRegs(std::cerr);                                    \
To delete

2023-11-23 20:12 UTC, Vokerlee commented on simulator/hart/hart.cpp
> +    // All basic blocks ends with branch instruction
ends -> end

2023-11-23 20:12 UTC, Vokerlee commented on simulator/hart/hart.cpp
> +    for (auto it: instructions) {
To delete

2023-11-23 20:15 UTC, Vokerlee requested changes

2023-11-23 20:15 UTC, Vokerlee commented on simulator/hart/basic_block.h
> +    static constexpr size_t DEFAULT_BB_CACHE_SIZE = 1 << 8;
Add to `common/config.h`, please

2023-11-25 13:29 UTC, Stan1slavssKy commented on simulator/hart/basic_block.h
> +    Instruction *AddInstruction()
done

2023-11-25 13:29 UTC, Stan1slavssKy commented on simulator/hart/basic_block.h
> +        BasicBlock *bb = cache_[pc % CACHE_SIZE];
done

2023-11-25 13:29 UTC, Stan1slavssKy commented on simulator/hart/basic_block.h
> +        cache_[start_pc % CACHE_SIZE] = bb;
done

2023-11-25 13:33 UTC, Stan1slavssKy commented on simulator/hart/basic_block.cpp
> +        if (instr->IsBranch()) {
In this case it is bad

2023-11-25 13:33 UTC, Stan1slavssKy commented on simulator/hart/basic_block.cpp
> +        instr->pc = curr_pc;
No, done

2023-11-25 13:34 UTC, Stan1slavssKy commented on simulator/hart/hart.cpp
> +        DumpRegs(std::cerr);                                    \
done

2023-11-25 13:35 UTC, Stan1slavssKy commented on simulator/hart/hart.cpp
> +    // All basic blocks ends with branch instruction
OK

2023-11-25 13:35 UTC, Stan1slavssKy commented on simulator/hart/hart.cpp
> +    for (auto it: instructions) {
OK

2023-11-25 13:35 UTC, Stan1slavssKy commented on simulator/hart/basic_block.h
> +    static constexpr size_t DEFAULT_BB_CACHE_SIZE = 1 << 8;
done

2023-11-25 14:40 UTC, Stan1slavssKy commented on simulator/hart/basic_block.h
> +    BasicBlock *GetBBFromCache(size_t pc) const
I think its normal that in Interpret(), basic block manager will return non-const BasibBlock from GetNextBB()

2023-11-25 14:41 UTC, Stan1slavssKy commented
@Vokerlee PTAL

2023-11-25 14:41 UTC, Stan1slavssKy commented
@Hollbrok PTAL

2023-11-25 14:43 UTC, Vokerlee approved these changes

2023-11-25 14:49 UTC, Hollbrok approved these changes
great work

2023-11-25 14:52 UTC, merged